image: node:8.6.0 

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

pages:
  stage: deploy
  script:
    - yarn build:gh
    - rm -rf public
    - mv dist/ public/
  artifacts:
    paths:
      - public 
  only:
    - master 
